prompt 
prompt STORE
desc F18_17_STORE
prompt HAS
desc F18_17_HAS
prompt ALBUM
desc F18_17_ALBUM
prompt EMPLOYEE
desc F18_17_EMPLOYEE
prompt STORE MANAGER
desc F18_17_STORE_MANAGER
prompt CLERK
desc F18_17_CLERK
prompt HOURS WORKED
desc F18_17_HOURS_WORKED
prompt EMPLOYEE CONTACT INFO
desc F18_17_EMPLOYEE_CONTACT_INFO
prompt CUSTOMER
desc F18_17_CUSTOMER
prompt SUPPLIER
desc F18_17_SUPPLIER
prompt INDIVIDUAL
desc F18_17_INDIVIDUAL
prompt CUSTOMER CONTACT INFO
desc F18_17_CUSTOMER_CONTACT_INFO
prompt BUYS FROM
desc F18_17_BUYS_FROM
prompt SELLS TO
desc F18_17_SELLS_TO
